# Generated by Django 5.2 on 2025-04-16 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Failure_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.UUIDField(default=uuid.uuid4)),
                ('email_failure', models.IntegerField(default=0)),
                ('row_failure', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Input_Row',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processed_at', models.DateField(auto_now_add=True)),
                ('brand', models.CharField(choices=[('Oppo', 'Oppo'), ('Vivo', 'Vivo'), ('Xiaomi', 'Xiaomi'), ('Realme', 'Realme'), ('Samsung', 'Samsung')], editable=False, max_length=50)),
                ('jsonified_row_data', models.CharField(editable=False, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='N/A', editable=False, max_length=50)),
                ('email', models.EmailField(default='N/A', editable=False, max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('model_description', models.TextField(blank=True, default='N/A', null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, default='N/A', max_digits=10, null=True)),
                ('mop', models.DecimalField(blank=True, decimal_places=2, default='N/A', max_digits=10, null=True)),
                ('bank_name', models.CharField(blank=True, choices=[('HDFC CC', 'HDFC CC'), ('HDFC DC', 'HDFC DC'), ('ICICI CC', 'ICICI CC'), ('ICICI DC', 'ICICI DC'), ('AXIS CC', 'AXIS CC'), ('AXIS DC', 'AXIS DC'), ('UNIPAY CC', 'UNIPAY CC'), ('UNIPAY DC', 'UNIPAY DC'), ('CITIBANK CC', 'CITIBANK CC'), ('CITIBANK DC', 'CITIBANK DC'), ('STANDARD CHARTERED CC', 'STANDARD CHARTERED CC'), ('STANDARD CHARTERED DC', 'STANDARD CHARTERED DC'), ('HSBC CC', 'HSBC CC'), ('HSBC DC', 'HSBC DC'), ('KOTAK CC', 'KOTAK CC'), ('KOTAK DC', 'KOTAK DC'), ('SBI CC', 'SBI CC'), ('SBI DC', 'SBI DC'), ('AMEX CC', 'AMEX CC'), ('INDUSIND CC', 'INDUSIND CC'), ('INDUSIND DC', 'INDUSIND DC'), ('BAJAJ CC', 'BAJAJ CC'), ('BAJAJ DC', 'BAJAJ DC'), ('RBL CC', 'RBL CC'), ('RBL DC', 'RBL DC'), ('YES CC', 'YES CC'), ('YES DC', 'YES DC'), ('Bank of Baroda CC', 'Bank of Baroda CC'), ('Bank of Baroda DC', 'Bank of Baroda DC'), ('FEDERAL CC', 'FEDERAL CC'), ('FEDERAL DC', 'FEDERAL DC'), ('J&K CC', 'J&K CC'), ('J&K DC', 'J&K DC'), ('AU CC', 'AU CC'), ('AU DC', 'AU DC'), ('ONECARD CC', 'ONECARD CC'), ('IDFC FIRST CC', 'IDFC FIRST CC'), ('IDFC FIRST DC', 'IDFC FIRST DC')], max_length=100, null=True)),
                ('scheme_type', models.CharField(default='Brand EMI', max_length=50)),
                ('emi_type', models.CharField(blank=True, default='No Cost EMI', max_length=50, null=True)),
                ('emi_tenure', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('low_cost_emi_subvention', models.DecimalField(blank=True, decimal_places=2, default='N/A', max_digits=5, null=True)),
                ('cashback_type', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('cashback_amount', models.DecimalField(blank=True, decimal_places=2, default='N/A', max_digits=10, null=True)),
                ('max_cashback_amount', models.DecimalField(blank=True, decimal_places=2, default='N/A', max_digits=10, null=True)),
                ('promo_start_date', models.DateField(blank=True, default='N/A', null=True)),
                ('promo_end_date', models.DateField(blank=True, default='N/A', null=True)),
                ('scheme_id', models.CharField(blank=True, default='N/A', max_length=100, null=True, unique=True)),
                ('is_emi', models.BooleanField(default=False)),
                ('is_cashback', models.BooleanField(default=False)),
                ('is_upfront', models.BooleanField(blank=True, default=False, null=True)),
                ('emi_brand_subvention', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emi_bank_subvention', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cashback_brand_subvention', models.IntegerField(blank=True, default=0, null=True)),
                ('cashback_bank_subvention', models.IntegerField(blank=True, default=0, null=True)),
                ('additional_terms', models.TextField(blank=True, default='N/A', null=True)),
                ('is_apporved', models.BooleanField(default=False)),
                ('jsonified_data', models.CharField(blank=True, max_length=500, null=True)),
                ('input_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='core.input_row')),
            ],
        ),
    ]
