# Generated by Django 5.2 on 2025-04-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='is_apporved',
            new_name='is_approved',
        ),
    ]
