# Generated by Django 5.2 on 2025-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_apporved_scheme_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='additional_terms',
            field=models.CharField(blank=True, default='N/A', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='cashback_amount',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='cashback_bank_subvention',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='cashback_brand_subvention',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='emi_bank_subvention',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='emi_brand_subvention',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='low_cost_emi_subvention',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='max_cashback_amount',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='model_description',
            field=models.CharField(blank=True, default='N/A', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='mop',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='mrp',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='promo_end_date',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='promo_start_date',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
