# Generated by Django 5.2 on 2025-04-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_scheme_additional_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='input_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='core.input_row'),
        ),
    ]
