# Generated by Django 5.2 on 2025-04-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_scheme_input_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='scheme_id',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
