# Generated by Django 5.2 on 2025-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_scheme_scheme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='sku',
            field=models.CharField(max_length=100),
        ),
    ]
