# Generated by Django 5.2 on 2025-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_scheme_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(editable=False, max_length=50, null=True)),
                ('email', models.EmailField(editable=False, max_length=100, null=True)),
                ('password', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
