# Generated by Django 5.2 on 2025-04-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_model_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Model',
            new_name='Manager',
        ),
    ]
