# Generated by Django 5.2 on 2025-04-17 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_user_model_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
