# Generated by Django 5.2 on 2025-04-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
