# Generated by Django 5.2 on 2025-04-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_manager_email_alter_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_row',
            name='jsonified_row_data',
            field=models.CharField(max_length=1000),
        ),
    ]
