# Generated by Django 5.2 on 2025-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_input_row_jsonified_row_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='jsonified_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
