# Generated by Django 5.2 on 2025-05-06 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_email_emailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='processed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='input_row',
            name='email_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_rows', to='core.emailattachment'),
        ),
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='input_row',
            name='jsonified_row_data',
            field=models.CharField(max_length=2000),
        ),
    ]
