# Generated by Django 5.2 on 2025-05-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_email_processed_email_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='name',
            field=models.CharField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
